config/routes.rb
Myvolume::Application.routes.draw do

  resources :charts
  resources :artists
  resources :songs
  resources :users
  resources :sessions

  match "/topdownloads" => "charts#top_downloads"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  

  root :to => "home#index"
  

end

app/models/chart.rb
class Chart < ActiveRecord::Base
  
  has_many :chart_memberships
  has_many :songs, :through => :chart_memberships
  
  has_many :chart_genre_memberships
  has_many :genres, :through => :chart_genre_memberships
  
  has_one :chart_thumbnail
  
  self.per_page = 6
  
  def self.fetch_chart_detail(charts)
    artist_list = []
    charts.each do |chart|
      
      # Fetch Chart Detail with newest.id
      chart_detail_fetch = Net::HTTP.get_response(URI.parse("http://api.beatport.com/catalog/charts/detail?id=#{chart["id"]}&format=json&v=1.0"))
      chart_detail_data = chart_detail_fetch.body
      chart_detail = JSON.parse(chart_detail_data)

      #print "#{newest["name"]} ~ #{newest["description"].gsub('\n','')}\n"
      chart_object = Chart.first(:conditions => {:name => chart["name"]})
      
      # Check to see if chart already exists, and if the chart is older than one year old
      if chart_object.nil?
        chart_object = Chart.new(:name => chart["name"], :beatport_id => chart["id"], 
                                 :description => chart["description"], :publish_date => chart["publishDate"])
        chart_object.save
        chart_detail["results"]["genres"].each do |genre|
          genre_object = Genre.first(:conditions => {:name => genre["name"]})
          # Check to see if the genre exists
          if genre_object.nil?
            genre_object = Genre.new(:name => genre["name"], :slug => genre["slug"])
            genre_object.save
          end
          # Check to see if the membership already exists
          chart_genre_object = ChartGenreMembership.first(:conditions => {:genre_id => genre_object.id, :chart_id => chart_object.id})
          if chart_genre_object.nil?
            chart_genre_object = ChartGenreMembership.new(:chart_id => chart_object.id, :genre_id => genre_object.id)
            chart_genre_object.save
          end
        end
        # Create chart thumbnail
        # Depending on if the call is being made from catalog or overview, the object may not have a large thumbnail
        if chart_detail["results"]["images"]["large"].nil?
          chart_thumb_object = ChartThumbnail.new(:chart_id => chart_object.id, :small => chart_detail["results"]["images"]["small"]["url"],
                                              :medium => chart_detail["results"]["images"]["medium"]["url"])
          chart_thumb_object.save
        elsif !chart_detail["results"]["images"]["large"].nil?
          chart_thumb_object = ChartThumbnail.new(:chart_id => chart_object.id, :small => chart_detail["results"]["images"]["small"]["url"],
                                              :medium => chart_detail["results"]["images"]["medium"]["url"],
                                              :large => chart_detail["results"]["images"]["large"]["url"])
          chart_thumb_object.save
        end
        # Iterate through each track of every chart
        chart_detail["results"]["tracks"].each_with_index do |track,i| 
          artists = ""
          remixer = ""
          # Check to see if the song already exists
          song_object = Song.first(:conditions => {:beatport_id => track["id"]})
          if song_object.nil?
            song_object = Song.new(:name => track["name"], :mix_name => track["mixName"], :sample_url => track["sampleUrl"], :beatport_id => track["id"],
                                   :length => track["length"], :release_date => track["releaseDate"], :publish_date => track["publishDate"])
            song_object.save
          end
          # Create song - chart association 
          chart_membership_object = ChartMembership.new(:song_id => song_object.id, :chart_id => chart_object.id, :pos => i+1)
          chart_membership_object.save
          # Iterate through song genre associations
          track["genres"].each do |genre|
            # Check to see if genre already exists
            genre_object = Genre.first(:conditions => {:name => genre["name"]})
            if genre_object.nil?
              genre_object = Genre.new(:name => genre["name"], :slug => genre["name"])
            end
            # Create song - genre association
            genre_membership_object = GenreMembership.new(:genre_id => genre_object.id, :song_id => song_object.id)
            genre_membership_object.save
          end
          # Loop through the artists
          artists = []
          track["artists"].each do |artist|
            # artist_list is use to fetch more accurate data on each newly added artist
            #I haven't completed this functionality yet
            artist_list << artist["id"]
            artists << artist["name"]
            if artist["type"] == "Remixer"
              remixer = artist["name"]
            end
            # Check to see if artist already exists
            artist_object = Artist.first(:conditions => {:name => artist["name"]})
            # If it doesn't exist
            if artist_object.nil?
              artist_object = Artist.new(:name => artist["name"], :beatport_id => artist["id"], :type => artist["type"],
                                         :last_publish_date => artist["lastPublishDate"],
                                         :bio => artist["biography"])
              artist_object.save
            end
              # Add membership between song and artist
              membership_object = Membership.new(:artist_id => artist_object.id, :song_id => song_object.id, :type => artist["type"])
              membership_object.save
          end
          # Join artist list on ampersand
          #Inefficient, on the list to change
          song_object.artist = artists.join(' & ')
          song_object.remixer = remixer
          song_object.save
          
          # Grab thumbnail information for each song
          song_thumb_object = SongThumbnail.first(:conditions => {:song_id => song_object.id})
          if !song_object.nil? && !track["images"].nil? && !track["images"]["large"].nil?
            song_thumb_object = SongThumbnail.new(:song_id => song_object.id,
                                                  :small => track["images"]["small"]["url"],
                                                  :medium => track["images"]["medium"]["url"],
                                                  :large => track["images"]["large"]["url"])
            song_thumb_object.save
          end
        end
      end
    end
    return artist_list
  end
  
  def self.fetch_charts
    json_out = {}
    artist_list = []
    
    # Fetch Chart Overview JSON from Beatport
    chart_overview_fetch = Net::HTTP.get_response(URI.parse("http://api.beatport.com/catalog/charts/overview?format=json&v=1.0"))
    chart_overview_data = chart_overview_fetch.body
    chart_overview = JSON.parse(chart_overview_data)
    
    # Iterate through newewst & featured charts
    artist_list << fetch_chart_detail(chart_overview["results"]["newest"])
    artist_list << fetch_chart_detail(chart_overview["results"]["featured"])
    
    @genres = Genre.all
       @genres.each do |genre|
         chart_overview_fetch = Net::HTTP.get_response(URI.parse("http://api.beatport.com/catalog/charts?sortBy=publishDate%20desc,chartId%20desc&genreId=#{genre.id}&perPage=5&page=1&format=json&v=1.0"))
         chart_overview_data = chart_overview_fetch.body
         chart_overview = JSON.parse(chart_overview_data)
         artist_list << fetch_chart_detail(chart_overview["results"])
       end
    # Filter duplicates from artist IDs
    artist_list = artist_list.to_set
    
    # Update last_update
    cron_watcher_object = CronWatcher.new(:last_update => Time.now)
    cron_watcher_object.save
    
    #fill_artist_info(artist_list.to_a)
  end
  
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  #attr_accessible 
  # GET /charts
  # GET /charts.xml

  def snippet(title, wordcount)  
    title.split[0..(wordcount-1)].join(" ") + (title.split.size > wordcount ? "..." : "") 
  end

  def index
    if !params[:top].nil?
      @charts = Chart.where("id <= :id",{:id => params[:top]}).paginate(:page => params[:page], :order => "publish_date desc")
    else
      @charts = Chart.paginate(:page => params[:page], :order => "publish_date desc")
    end

    
    @data = []
    @charts.each do |chart|
      @thumbnails = {"thumbnail_small"=>chart.chart_thumbnail.small, "thumbnail_medium"=>chart.chart_thumbnail.medium, "name_truncated" => snippet(chart.name,4)}
      @genres = {"genres"=> chart.genres.map {|genre| genre.name }}
      @data << chart.attributes.merge!(@thumbnails).merge!(@genres)
    end

    render :json => @data.to_json
  end

  def charts_paginate
    @charts = Chart.paginate :page => params[:chart_page], :order => "publish_date desc"
  end

  # GET /charts/1
  # Will is the best!
  # GET /charts/1.xml
  def show
    @chart = Chart.find(params[:id])
    @data = @chart.songs.map { |song| song.attributes }

    render :json => @data.to_json
  end

  def top_downloads
    @topdownloads = TopDownload.paginate :page => params[:page], :order => "rank asc"
    @data = []
    @topdownloads.each {|td| @data << td.song }

    render :json => @data.to_json
  end
  
  def showSongs
    @songs = Chart.find(params[:id]).songs
    
    respond_to do |format|
      format.js
      format.html # index.html.erb
      format.xml  { render :xml => @songs }
    end
  end
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/views/charts/_chart_songs.html.erb
<% if !@songs.nil? %>
<table>
    <% @songs.each do |song| %>
      <tr class="play <%= song.id %>" name="<%= song.sample_url %>" class="#{song.id}">
          <%= render 'songs/song', :song => song %>
      </tr>
    <% end %>
</table>
<% end %>

app/views/charts/_charts.html.erb
<div id = "charts">
  <div id = "chart_pagination">
    <%= render 'charts/pagination' %>
  </div>
  <div class="chart_list">
    <% @charts.each do |chart| %>
      <div class="chart clearfix" <%= "name=/charts/#{chart.id}/get" %> title="<%= chart.name %>">
      <div class="clearfix top">
        <%= image_tag chart.chart_thumbnail.small %>
        <div class="chart_text">
          <div class="title">
            <span class="label success">New</span>
            <%= truncate(chart.name, :length => 40) %>
          </div>
        </div><!-- /chart_text -->
      </div>
          <div class="genres">
            <% chart.genres.each do |genre| %>
              <span class="genre">
                <% if genre.name.length > 12 %>
                  <%= truncate(genre.name, :length => 12, :separator => ' ', :omission => '') %>
                <% else %>
                  <%= genre.name %>
                <% end %>
              </span>
            <% end %>
          </div>
      </div>
    <% end %>
  </div><!-- /chart_list -->
</div>
<div id = "chart_songs">
  <%= render "chart_songs" %>
</div>

app/views/charts/_form.html.erb
<%= form_for(@chart) do |f| %>
  <% if @chart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chart.errors.count, "error") %> prohibited this chart from being saved:</h2>

      <ul>
      <% @chart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charts/_pagination.html.erb
<%= will_paginate @charts, :class => "pagination charts", :param_name => "chart_page", :previous_label => 'Previous', :next_label => 'Next', :method => :charts_paginate %>

app/views/charts/_recent_loves.html.erb
<h2>Recent Favorites</h2>
<div class="chart_outside">
<div class="chart_list">
</div><!-- /chart_list -->
<div class="clear"></div>  
</div><!-- /chart_outside -->
  

app/views/charts/charts_paginate.js.erb
$("#chart_pagination").html("<%= escape_javascript(render('charts/pagination')) %>");

app/views/charts/edit.html.erb
<h1>Editing chart</h1>

<%= render 'form' %>

<%= link_to 'Show', @chart %> |
<%= link_to 'Back', charts_path %>

app/views/charts/index.html.erb
<div id="chart_wrapper" class="clearfix">
<%= render 'charts' %>
</div>

app/views/charts/index.js.erb
$("#chart_wrapper").html("<%= escape_javascript(render('charts/charts')) %>").hide().fadeIn();
/*$("#chart_pagination").html("<%= escape_javascript(render('charts/pagination')) %>");
/*var $list = $('.chart_outside');
$list.css('left', -$list.outerWidth() + 'px');
$list.animate({
   left: parseInt($list.css('left'),10) == 0 ? -$list.outerWidth() :0
});*/     

app/views/charts/new.html.erb
<h1>New chart</h1>

<%= render 'form' %>

<%= link_to 'Back', charts_path %>

app/views/charts/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_chart_path(@chart) %> |
<%= link_to 'Back', charts_path %>

app/views/charts/showSongs.js.erb
$("#chart_songs").hide();
$("#chart_songs").html("<%= escape_javascript(render('charts/chart_songs')) %>").fadeIn();