config/routes.rb
Myvolume::Application.routes.draw do

  resources :charts
  resources :artists
  resources :songs
  resources :users
  resources :sessions

  match "/topdownloads" => "charts#top_downloads"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  

  root :to => "home#index"
  

end

app/models/song.rb
class Song < ActiveRecord::Base
  
  has_many :memberships
  has_many :artists, :through => :memberships
  
  has_many :chart_memberships
  has_many :charts, :through => :chart_memberships
  
  has_many :genre_memberships
  has_many :genres, :through => :genre_memberships
  
  has_many :favorites
  has_many :users, :through => :favorites
  
  has_many :authorization_favorites
  has_many :authorizations, :through => :authorization_favorites
  
  has_one :song_thumbnail
  belongs_to :label
  
  has_one :top_download
  
  
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  #before_filter :authenticate_user!
  # GET /songs
  load_and_authorize_resource :only => [:edit, :create, :update, :destroy]
  # GET /songs.xml
  def index
    @chart = Chart.find(params[:chart_id])

    @data = []
    @chart.songs.each {|song| @data << song.attributes.merge!({"thumbnail_small"=>song.song_thumbnail.small}).merge!({"genre"=>song.genres.first.name})}

    render :json => @data.to_json
  end

  # GET /songs/1
  # GET /songs/1.xml
  def show
    @song = Song.find(params[:id])
  end

  def top_downloads
    @top_downloads = TopDownload.paginate :page => params[:top_download_page], :order => "rank asc"
  end
  # GET /songs/new
  # GET /songs/new.xml
  def new
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @song }
    end
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/_showTrack.html.erb
<div class="box">
	<ul class="directory">
		<li><%= link_to "Back", root_url, :class => "showhome" %></li>
		<li> ⇒ <%= link_to "View Track",song_path(@song), :class => "showtrack" %></li>
	</ul>
		
	<div class="track_image">
		<%= image_tag @song.song_thumbnail.large %>
	</div>
	<div id="disqus_thread"></div>
</div>
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'myvolume'; // required: replace example with your forum shortname

    // The following are highly recommended additional parameters. Remove the slashes in front to use.
    // var disqus_identifier = 'unique_dynamic_id_1234';
    // var disqus_url = 'http://example.com/permalink-to-page.html';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
<!-- <script>
$(document).ready(function(){
	window.disqus_no_style = true;
	$.getScript("http://myvolume.disqus.com/embed.js")
});
</script> -->

app/views/songs/_song.html.erb
<td class="thumb">
<% if !!song.song_thumbnail %>
  <%= image_tag song.song_thumbnail.small %>
<% end %>
</td>

<td>
<% if !!song.name and !!song.mix_name %>
  <div class="song_name"><%= song.name %></div>
  <div class="mix_name">(<%= song.mix_name %>)</div>
<% end %>
</td>

<td class="artist">
<% if !!song.artist %>
  <%= song.artist  %>
<% end %>
</td>

<td class="genre">
<% if !!song.genres %>
  <% if song.genres.first.id == 15 %>
    <% @s = song.genres.first.name.split(' / ') %>
    <div class="genre">
      <%= @s[0] %>
    </div>
    <div class="genre">
    <%= @s[-1] %>
    </div>
  <% else %>
    <div class="genre"><%= song.genres.first.name  %></div>
  <% end %>
<% end %>
</td>


<% if is_favorite(song.id) %>
  <td class="heart active" url="/favorite/<%= song.id %>">
<% else %>
  <td class="heart" url="/favorite/<%= song.id %>">
<% end %>
</td>

<td class="download" url="<%= generateQuery(song) %>"></td>

app/views/songs/_top_downloads.html.erb
<div id="top_downloads">
<%= will_paginate @top_downloads, :class => "pagination top-downloads", :param_name => "top_download_page", :previous_label => 'Previous', :next_label => 'Next' %>
<% if !@top_downloads.nil? %>
<table>
    <% @top_downloads.each do |top| %>
      <tr class="play <%= top.song.id %>" name="<%= top.song.sample_url %>" class="#{top.song.id}">
          <%= render 'songs/top_song', :ranked => top %>
      </tr>
    <% end %>
</table>
<% end %>
</div>

app/views/songs/_top_song.html.erb
<td class="ranked"><%= ranked.rank.to_s.rjust(2, '0') %></td>
<% if ranked.difference > 0 %>
  <td class="positive"><%= "+#{ranked.difference}" %></td>
<% elsif ranked.difference < 0 %>
  <td class="negative"><%= "#{ranked.difference}" %></td>
<% else %>
  <td><%= "#{ranked.difference}" %></td>
<% end %>

<td class="thumb">
<% if !!ranked.song.song_thumbnail %>
  <%= image_tag ranked.song.song_thumbnail.small %>
<% end %>
</td>

<td>
<% if !!ranked.song.name and !!ranked.song.mix_name %>
  <div class="song_name"><%= ranked.song.name %></div>
  <div class="mix_name">(<%= ranked.song.mix_name %>)</div>
<% end %>
</td>

<td class="artist">
<% if !!ranked.song.artist %>
  <%= ranked.song.artist  %>
<% end %>
</td>

<td class="genre">
<% if !!ranked.song.genres %>
  <% if ranked.song.genres.first.id == 15 %>
    <% @s = ranked.song.genres.first.name.split(' / ') %>
    <div class="genre">
      <%= @s[0] %>
    </div>
    <div class="genre">
    <%= @s[-1] %>
    </div>
  <% else %>
    <div class="genre"><%= ranked.song.genres.first.name  %></div>
  <% end %>
<% end %>
</td>


<% if is_favorite(ranked.song.id) %>
  <td class="heart active" url="/favorite/<%= ranked.song.id %>">
<% else %>
  <td class="heart" url="/favorite/<%= ranked.song.id %>">
<% end %>
</td>

<td class="download" url="<%= generateQuery(ranked.song) %>"></td>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Listing songs</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @songs.each do |song| %>
  <tr>
    <td><%= link_to 'Show', song %></td>
	<% if can? :update, song %>
    	<td><%= link_to 'Edit', edit_song_path(song) %></td>
	<% end %>
	<% if can? :destroy, song %>
    	<td><%= link_to 'Destroy', song, :confirm => 'Are you sure?', :method => :delete %></td>
	<% end %>
  </tr>
<% end %>
</table>

<br />

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.js.erb
$("#content_wrapper").html("<%= escape_javascript(render('songs/showTrack')) %>");

app/views/songs/top_downloads.html.erb
<div id="top-downloads">
  <%= render 'songs/top_downloads' %>
</div>

app/views/songs/top_downloads.js.erb
$("#content").html("<%= escape_javascript(render('songs/top_downloads')) %>");